### ISSUE TITLE
css-loader

### ISSUE THREAD

**Issue by safarishi** [Lucifier129/react-imvc-template#2]
目前同构的框架，在使用时，有一个痛点，调整css样式的内联写法

虽然现在不写css但是还是不可避免要写内联css,我在想为什么不在我们的webpack.config.js里面加上一个css loader然后把modules打开，这样写内联样式时就可以更加方便了，且还能实现模块化的功能

**Comment by Lucifier129** [comment]
css-loader 是 webpack only 的东西，node.js 里面 import 一个 css 文件会有问题，除非先用 webpack 编译一个 server.bundle.js，但这样会让整个应用更为复杂。

除了内联 css 之外，其实还有一个选择，就是用 react 写 style 组件，比如[这里的做法](https://github.com/Lucifier129/react-imvc-template/blob/master/react-imvc/component/DatePicker/style.js)

**Comment by safarishi** [comment]
css-loader也可以使用在服务端
https://github.com/css-modules/css-modules
其实现有 webpack, Server-side and static websites

**Comment by Lucifier129** [comment]
CSS 的主要工作不在我们团队里，为了一个少量的内联 css 处理去添加 css-loader，成本和收益不成正比。

如果有项目是 html css js 都由一个团队维护，到时再 react-imvc/build/webpack.config.js 里添加一下，也很方便。

**Comment by Lucifier129** [comment]
不使用 css-loader 等插件的原因：

- webpack-only 的插件，将导致业务代码跟构建工具的强耦合，使我们将来替换为其他工具比如 browserify, rollup 或其他新构建工具时，迁移成本变高

- css 暂时没有标准化的模块和局部作用域规范，在 js 里用 `import 'xxx.css'` 的做法，将来注定是要改变的。

- 以 hack 的方式解决目前并不紧要的 css 问题，有过度工程化的嫌疑。
